server:
  port: 80

spring:
  application:
    name: cloud-order-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/computer
    username: root
    password: 981121
  cloud:
    zookeeper:
      connect-string: hadoop100:2181